name: Generate Snake Contribution

on:
  schedule:
    - cron: "0 0 * * *"  # 每天运行
  workflow_dispatch:     # 允许手动触发

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # 必须添加写入权限
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: main      # 或你的默认分支名
        
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
          
      - name: Commit and push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist
          git commit -m "Update snake contribution graph"
          git push
